name: Testing

on:
  push:
    paths-ignore:
      - ".vscode/**"
      - "*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "*.md"
      - "LICENSE"

jobs:
  cypress:
    name: Cypress End-to-End
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          config-file: tests/cypress/config.json
          build: yarn build
          start: yarn serve
          wait-on: http://localhost:2020
